#!/bin/sh

netIface="wan"					#network interface to use
lockFile="/var/run/gatekeeperUpdate.lock"	#the lockfile
ipFile="/tmp/gatekeeperIp.txt"			#file to store the ip in

if [ "$ACTION" = "ifup" ] && [ "$INTERFACE" = "${netIface}" ]; then
	{
		. /lib/functions/network.sh;
		if [ ! -f "${lockFile}" ]; then
			touch "${lockFile}"
			sleep 15
			ip=''
			network_get_ipaddr ip "${netIface}"
			echo "${ip}" | grep -E '^[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}' > /dev/null
			if [ $? -ne 0 ]; then
				rm "${lockFile}"
				return 0
			fi
			echo "${ip}" | grep -E '^(10\.|192\.168\.|172\.(1[6-9]|2[0-9]|3[01])\.)' > /dev/null && wanC=0 || wanC=1
			if [ $wanC -eq 1 ]; then
				touch "${ipFile}"
				grep "${ip}" "${ipFile}" > /dev/null
				if [ $? -eq 0 ]; then
					rm "${lockFile}"
					return 0
				fi
			fi
			/sbin/gatekeeperUpdate && {
				[ $wanC -eq 1 ] && echo "${ip}" > "${ipFile}"
			}
			rm "${lockFile}"
		fi
	}&
fi
