#!/bin/sh

isOk() {
	echo ""
	while true; do
		read -r -p "${1} (y|n): " choice
		case "$choice" in
			n|N) echo "ok Bye, exiting now" ;exit;;
			y|Y) break;;
			*) echo 'Response not valid';;
		esac
	done
}

q="opkg update"
echo "Checking if wget is installed"
inst=`opkg list-installed wget`
if [ $? -eq 127 ]; then
	echo "Are you sure this is OpenWrt?, opkg isn't found" 1>&2
	exit 1
fi

[ -z "${inst}" ] && inst=`opkg list-installed curl`

if [ -z "${inst}" ]; then
	inst=`opkg list-installed wget-nossl`
	if [ ! -z "${inst}" ]; then
		echo "wget-nossl is currently installed, but we need https support!"
		isOk "Do you want to remove wget-nossl and install wget?"
		q="${q}"$'\nopkg remove wget-nossl'
	else
		isOk "wget is currently not installed, is it ok to install it?"
	fi
	q="${q}"$'\nopkg install wget'
	echo "${q}" | while read cmd; do
		${cmd} || {
			echo "Installation if wget has failed, exiting script"
			exit 1
		}
        done
fi

tmpFile=`mktemp`

#get and load the rest from the script from the git repo
echo "${inst}" | grep 'curl' > /dev/null
if [ $? -eq 0 ]; then
	curl --insecure -o "${tmpFile}" "https://raw.github.com/FriedZombie/tunlrUpdater/master/gatekeeper/OpenWrt/insTunlr-git"
else
	wget --no-check-certificate -O "${tmpFile}" "https://raw.github.com/FriedZombie/tunlrUpdater/master/gatekeeper/OpenWrt/insTunlr-git"
fi

if [ $? -ne 0 ]; then
	echo "Downloading the second part of the script has failed"
	exit 1
fi
. "${tmpFile}"
